### ISSUE TITLE
Salasanan palauttamisen sivut

### ISSUE THREAD

**Issue by Akzuu** [Tampereen-Urheilusukeltajat/Blenderi-UI#28]
Sovelluksen käyttäjänä haluan, että

- Jos en muista salasanaani kirjautumisnäkymässä, voin klikata linkkiä joka ohjaa minut salasanan palautukseen
- Tässä näkymässä voin antaa sähköpostini, johon olen tehnyt tunnuksen
- Lähetettyäni sähköpostin, nään geneerisen "Sähköposti lähetetty jos käyttäjä on olemassa hehe" näkymän

- Kun klikkaan linkkiä saamastani sähköpostista, minut ohjataan näkymään jossa voin asettaa uuden salasanan
- Salasanan vaihtamisen jälkeen minut ohjataan kirjautumisnäkymään

![Image](https://user-images.githubusercontent.com/33838340/207308286-75d77022-f46a-4427-a1ad-6cf3db477c34.png)

**Comment by ilesoft** [comment]
## pohdintoja muualta

Meidän pitää rajoittaa käyttäjälle lähtevien sähköpostien määrää tilanteessa, jossa joku pahanilkinen osapuoli tekee 1000000 kpl salasanaresetpyyntöjä uhrin sähköpostiosoitteella.

Mut sit kun ottaa huomioon millainen media sähköposti on niin ei sitä voi oikein yhteenkään kappaleeseen rajoittaa

Ekana tuli mieleen, että sallittais ~5 voimassa olevaa tokenia (=max ~5 sähköpostia per tokenin voimassaoloaika tms.) ja loput resetpyynnöt menis suoraan roskiin

Voimassa olevien tokenien tallentamiseen tullaan käyttämään redisiä kun se kerron jo löytyy teknologiapinosta. Ja se että tokenit katoaa mahdollisen uudelleenkäynnistyksen yhteydessä ei pitäisi olla ongelma.

**Comment by ilesoft** [comment]
Täähän tuli valmiiksi PR:ssä #57
